=== souhailsboui/magento2/src/app/code/MageMe/WebForms/etc/webforms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="webforms">
        <xs:annotation>
            <xs:documentation>
                The root node for webforms configuration.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element name="field_types" type="field_typesType" minOccurs="0"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="field_typesType">
        <xs:annotation>
            <xs:documentation>
                The containing node for a list of field types.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="type" type="typeType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="typeType">
        <xs:annotation>
            <xs:documentation>
                The definition of a field type.
            </xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:element name="value" type="xs:string" minOccurs="0"/>
            <xs:element name="logic" type="xs:boolean" minOccurs="0"/>
            <xs:element name="attributes" type="typeAttributes" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="order" type="xs:integer" use="required"/>
    </xs:complexType>

    <xs:complexType name="typeAttributes">
        <xs:annotation>
            <xs:documentation>
                The containing node for a list of field type attributes.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="attribute" type="typeAttribute"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="typeAttribute">
        <xs:annotation>
            <xs:documentation>
                The definition of a type attribute.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== souhailsboui/magento2/src/app/code/MageMe/WebForms/etc/webforms.xml
<?xml version="1.0"?>
<webforms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="urn:magento:module:MageMe_WebForms:etc/webforms.xsd">
    <field_types>
        <type id="text"
              order="0">
            <label>Text</label>
            <model>MageMe\WebForms\Model\Field\Type\Text</model>
            <category>Text</category>
            <value>text</value>
            <attributes>
                <attribute name="placeholder"/>
                <attribute name="text"/>
                <attribute name="customer_data"/>
                <attribute name="mask"/>
                <attribute name="case_transform"/>
            </attributes>
        </type>
        <type id="email"
              order="10">
            <label>Email</label>
            <model>MageMe\WebForms\Model\Field\Type\Email</model>
            <category>Text</category>
            <attributes>
                <attribute name="placeholder"/>
                <attribute name="mask"/>
                <attribute name="is_filled_by_customer_email"/>
                <attribute name="is_assigned_customer_id_by_email"/>
                <attribute name="email_match_value_field_id"/>
                <attribute name="case_transform"/>
            </attributes>
        </type>
        <type id="number"
              order="20">
            <label>Number</label>
            <model>MageMe\WebForms\Model\Field\Type\Number</model>
            <category>Text</category>
            <attributes>
                <attribute name="placeholder"/>
                <attribute name="min"/>
                <attribute name="max"/>
            </attributes>
        </type>
        <type id="url"
              order="30">
            <label>URL</label>
            <model>MageMe\WebForms\Model\Field\Type\Url</model>
            <category>Text</category>
            <value>text</value>
            <attributes>
                <attribute name="placeholder"/>
                <attribute name="text"/>
                <attribute name="mask"/>
                <attribute name="case_transform"/>
            </attributes>
        </type>
        <type id="password"
              order="40">
            <label>Password</label>
            <model>MageMe\WebForms\Model\Field\Type\Password</model>
            <category>Text</category>
            <attributes>
                <attribute name="placeholder"/>
                <attribute name="is_encrypt"/>
                <attribute name="is_complexity_enabled"/>
                <attribute name="min_password_length"/>
                <attribute name="complexity_symbols_count"/>
                <attribute name="password_match_value_field_id"/>
            </attributes>
        </type>
        <type id="autocomplete"
              order="50">
            <label>Auto-complete</label>
            <model>MageMe\WebForms\Model\Field\Type\Autocomplete</model>
            <category>Text</category>
            <value>text</value>
            <attributes>
                <attribute name="placeholder"/>
                <attribute name="text"/>
                <attribute name="mask"/>
                <attribute name="case_transform"/>
            </attributes>
        </type>
        <type id="textarea"
              order="60">
            <label>Textarea</label>
            <model>MageMe\WebForms\Model\Field\Type\Textarea</model>
            <category>Text</category>
            <value>text</value>
            <attributes>
                <attribute name="placeholder"/>
                <attribute name="text"/>
                <attribute name="customer_data"/>
                <attribute name="mask"/>
                <attribute name="rows"/>
                <attribute name="case_transform"/>
            </attributes>
        </type>
        <type id="wysiwyg"
              order="70">
            <label>WYSIWYG Editor</label>
            <model>MageMe\WebForms\Model\Field\Type\Wysiwyg</model>
            <category>HTML</category>
        </type>
        <type id="select"
              order="80">
            <label>Select</label>
            <model>MageMe\WebForms\Model\Field\Type\Select</model>
            <category>Select</category>
            <value>options</value>
            <logic>true</logic>
            <attributes>
                <attribute name="options"/>
                <attribute name="is_multiselect"/>
            </attributes>
        </type>
        <type id="select_radio"
              order="90">
            <label>Radio Group</label>
            <model>MageMe\WebForms\Model\Field\Type\SelectRadio</model>
            <category>Select</category>
            <value>options</value>
            <logic>true</logic>
            <attributes>
                <attribute name="options"/>
                <attribute name="is_internal_elements_inline"/>
            </attributes>
        </type>
        <type id="select_checkbox"
              order="100">
            <label>Checkbox Group</label>
            <model>MageMe\WebForms\Model\Field\Type\SelectCheckbox</model>
            <category>Select</category>
            <value>options</value>
            <logic>true</logic>
            <attributes>
                <attribute name="options"/>
                <attribute name="min_options"/>
                <attribute name="max_options"/>
                <attribute name="min_options_error_text"/>
                <attribute name="max_options_error_text"/>
                <attribute name="is_internal_elements_inline"/>
            </attributes>
        </type>
        <type id="select_contact"
              order="110">
            <label>Select Contact</label>
            <model>MageMe\WebForms\Model\Field\Type\SelectContact</model>
            <category>Select</category>
            <value>options</value>
            <logic>true</logic>
            <attributes>
                <attribute name="options"/>
            </attributes>
        </type>
        <type id="country"
              order="120">
            <label>Country</label>
            <model>MageMe\WebForms\Model\Field\Type\Country</model>
            <category>Select</category>
            <value>default_country</value>
            <attributes>
                <attribute name="default_country"/>
            </attributes>
        </type>
        <type id="region"
              order="121">
            <label>State / Province</label>
            <model>MageMe\WebForms\Model\Field\Type\Region</model>
            <category>Select</category>
            <attributes>
                <attribute name="country_field_id"/>
                <attribute name="country_code"/>
            </attributes>
        </type>
        <type id="subscribe"
              order="130">
            <label>Subscription Checkbox</label>
            <model>MageMe\WebForms\Model\Field\Type\Subscribe</model>
            <category>Newsletter</category>
            <attributes>
                <attribute name="text"/>
            </attributes>
        </type>
        <type id="date"
              order="140">
            <label>Date</label>
            <model>MageMe\WebForms\Model\Field\Type\Date</model>
            <category>Date</category>
            <attributes>
                <attribute name="placeholder"/>
                <attribute name="is_past_disabled"/>
                <attribute name="is_future_disabled"/>
                <attribute name="is_today_disabled"/>
                <attribute name="past_offset"/>
                <attribute name="future_offset"/>
                <attribute name="disabled_week_days"/>
                <attribute name="disabled_custom_dates"/>
                <attribute name="default_value"/>
            </attributes>
        </type>
        <type id="time"
              order="150">
            <label>Time</label>
            <model>MageMe\WebForms\Model\Field\Type\Time</model>
            <category>Date</category>
            <attributes>
                <attribute name="available_hours"/>
                <attribute name="available_minutes"/>
            </attributes>
        </type>
        <type id="date_dob"
              order="160">
            <label>Date of Birth</label>
            <model>MageMe\WebForms\Model\Field\Type\Dob</model>
            <category>Date</category>
            <attributes>
                <attribute name="placeholder"/>
                <attribute name="is_filled_by_customer_dob"/>
            </attributes>
        </type>
        <type id="stars"
              order="170">
            <label>Star Rating</label>
            <model>MageMe\WebForms\Model\Field\Type\Stars</model>
            <category>Rating</category>
            <value>init_stars</value>
            <attributes>
                <attribute name="init_stars"/>
                <attribute name="max_stars"/>
            </attributes>
        </type>
        <type id="file"
              order="180">
            <label>File Upload</label>
            <model>MageMe\WebForms\Model\Field\Type\File</model>
            <category>File</category>
            <attributes>
                <attribute name="is_dropzone"/>
                <attribute name="dropzone_text"/>
                <attribute name="dropzone_max_files"/>
                <attribute name="allowed_extensions"/>
                <attribute name="allowed_size"/>
            </attributes>
        </type>
        <type id="image"
              order="190">
            <label>Image Upload</label>
            <model>MageMe\WebForms\Model\Field\Type\Image</model>
            <category>File</category>
            <attributes>
                <attribute name="is_dropzone"/>
                <attribute name="dropzone_text"/>
                <attribute name="dropzone_max_files"/>
                <attribute name="is_resized"/>
                <attribute name="resize_width"/>
                <attribute name="resize_height"/>
                <attribute name="allowed_size"/>
            </attributes>
